#!/usr/bin/env bash
set -euo pipefail

# Restore/write files from a markdown file generated by collect-staged-files-md.sh.
#
# Usage:
#   ./scripts/apply-md-file-changes.sh [input.md]
#   ./scripts/apply-md-file-changes.sh --dry-run [input.md]
#
# Default input file: staged-file-changes.md
#
# Expected markdown format:
#   #file changes
#
#   ## relative/file/path.ts
#
#   ````
#   full file code
#   ````
#
# For safety, only repository-relative paths are accepted. Absolute paths and
# paths containing ".." are rejected.

input_file="staged-file-changes.md"
dry_run=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run|-n)
      dry_run=1
      shift
      ;;
    --help|-h)
      sed -n '2,28p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      input_file="$1"
      shift
      ;;
  esac
done

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

if [[ ! -f "$input_file" ]]; then
  echo "Input markdown file not found: $input_file" >&2
  exit 1
fi

python3 - "$input_file" "$dry_run" <<'PY'
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

input_file = Path(sys.argv[1])
dry_run = sys.argv[2] == "1"
repo_root = Path.cwd().resolve()

header_re = re.compile(r"^##\s+(.+?)\s*\r?\n?$")
fence_re = re.compile(r"^(`{3,})(?:[^`]*)\r?\n?$")


def fail(message: str) -> None:
    print(message, file=sys.stderr)
    sys.exit(1)


def validate_relative_path(raw_path: str) -> Path:
    raw_path = raw_path.strip()

    if not raw_path:
        fail("Encountered an empty file path header.")

    path = Path(raw_path)

    if path.is_absolute():
        fail(f"Refusing to write absolute path: {raw_path}")

    if any(part == ".." for part in path.parts):
        fail(f"Refusing to write path containing '..': {raw_path}")

    target = (repo_root / path).resolve()
    try:
        target.relative_to(repo_root)
    except ValueError:
        fail(f"Refusing to write outside repository: {raw_path}")

    return target


def parse_markdown(lines: list[str]) -> list[tuple[str, str]]:
    files: list[tuple[str, str]] = []
    i = 0

    while i < len(lines):
        header_match = header_re.match(lines[i])
        if not header_match:
            i += 1
            continue

        rel_path = header_match.group(1).strip()
        i += 1

        # Find the first code fence after this file header. If the section has
        # no fence, it is probably a deleted/binary file note; skip it.
        while i < len(lines):
            if header_re.match(lines[i]):
                break

            start_match = fence_re.match(lines[i])
            if not start_match:
                i += 1
                continue

            fence = start_match.group(1)
            i += 1
            code_lines: list[str] = []

            while i < len(lines):
                # Closing fence must use the exact same backtick fence generated
                # by collect-staged-files-md.sh. This preserves any shorter
                # backtick runs inside the code content.
                if lines[i].rstrip("\r\n") == fence:
                    i += 1
                    files.append((rel_path, "".join(code_lines)))
                    break

                code_lines.append(lines[i])
                i += 1
            else:
                fail(f"Unclosed code fence for: {rel_path}")

            break

    return files


try:
    lines = input_file.read_text(encoding="utf-8").splitlines(keepends=True)
except UnicodeDecodeError as exc:
    fail(f"Failed to read {input_file} as UTF-8: {exc}")

files = parse_markdown(lines)

if not files:
    fail(f"No file code blocks found in: {input_file}")

for rel_path, code in files:
    target = validate_relative_path(rel_path)

    if dry_run:
        action = "update" if target.exists() else "create"
        print(f"[dry-run] Would {action}: {rel_path} ({len(code)} bytes)")
        continue

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(code, encoding="utf-8")
    print(f"Wrote: {rel_path}")

if dry_run:
    print(f"Dry run complete. {len(files)} file(s) parsed; no files were changed.")
else:
    print(f"Done. Wrote {len(files)} file(s).")
PY

